name: Deploy to Azure App Service (OIDC)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (dev/uat/prod)"
        required: true
        default: "dev"
      app_name:
        description: "Azure App Service name"
        required: true
      resource_group:
        description: "Azure Resource Group"
        required: true
      package_path:
        description: "Path to deploy artifact (zip folder or build output)"
        required: true
        default: "."

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      # OIDC login to Azure (no secrets)
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # Optional: Build steps go here (dotnet/pip/etc.) before deploy

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ inputs.app_name }}
          package: ${{ inputs.package_path }}
